export const robes = [
  {
    id:'1',
    name: "Robe",
    slug: "a-robe",
    category: "Vetement",
    image: "image/m1.jpg", // 679px × 829px
    price: 1199,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 20,
    description: "Une marque marocainne qui prends de jour en jour de l'empleure ",
    bg:"f5fafd",
  },
  {
    id:'2',
    name: "Robe Boubou",
    slug: "b-robe",
    category: "Vetement",
    image: "image/m2.jpg", // 679px × 829px
    price: 109,
    countInStock: 20,
    brand: "Nike",
    rating: 3.5,
    numReviews: 10,
    description: "Venez vous rendre belle  ",
    bg:"fcf1ed",

  },
  {
    id:'3',
    name: "Robe Ds",
    slug: "c-robe",
    category: "Vetement",
    image: "image/m3.jpg", // 679px × 829px
    price: 120,
    countInStock: 11,
    brand: "kiki",
    rating: 4.5,
    numReviews: 20,
    description: "Une marque qui vous rend encore et encore plus belle ",
    bg:'fbf0f4',
  },
  {
    id:'4',
    name: "Robe Long",
    slug: "d-robe",
    category: "Vetement",
    image: "image/m4.jpg", // 679px × 829px
    price: 1199,
    countInStock: 10,
    brand: "Awakiki",
    rating: 3.5,
    numReviews: 8,
    description: "On est la pour vous rendre belle ",
    bg:'fefaf4'
  },
  {
    id:'5',
    name: "Robe Grande",
    slug: "e-robe",
    category: "Vetement",
    image: "image/m5.jpg", // 679px × 829px
    price: 1199,
    countInStock: 10,
    brand: "Marque",
    rating: 4.5,
    numReviews: 20,
    description: "Une marque marocainne qui prends de jour en jour de l'empleure ",
    bg:"FFA07A"
  },

]
export const djnes =[
  {
    id:'1',
    name: "Djine Pour Tous",
    slug: "a-djine",
    category: "Vetement",
    image: "image/m6.jpg", // 679px × 829px
    price: 140,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 20,
    description: "Offre pour tous  ",
  },
  {
    id:'2',
    name: "Djines Home Femme",
    slug: "b-djne",
    category: "Vetement",
    image: "image/m7.jpg", // 679px × 829px
    price: 139,
    countInStock: 12,
    brand: "Puma",
    rating: 3.5,
    numReviews: 10,
    description: "Toujous Satisfait de nos offres",
  },
  {
    id:'3',
    name: "Pantalons",
    slug: "c-pantalon",
    category: "Vetement",
    image: "image/m8.jpg", // 679px × 829px
    price: 170,
    countInStock: 11,
    brand: "Nike",
    rating: 4.5,
    numReviews: 20,
    description: "Une marque qui vous rend encore et encore plus belle ",
  },
  {
    id:'4',
    name: "La Sape Chez nous",
    slug: "d-panta",
    category: "Vetement",
    image: "image/m9.jpg", // 679px × 829px
    price: 99,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Toujours à votre service",
  },
]

export const shirt= [
  {
    id:'1',
    name: "Djine Pour Tous",
    slug: "a-djine",
    category: "Vetement",
    image: "image/m10.jpg", // 679px × 829px
    price: 140,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 20,
    description: "Offre pour tous  ",
  },
  {
    id:'2',
    name: "Djines Home Femme",
    slug: "b-djne",
    category: "Vetement",
    image: "image/m11.jpg", // 679px × 829px
    price: 139,
    countInStock: 12,
    brand: "Puma",
    rating: 3.5,
    numReviews: 10,
    description: "Toujous Satisfait de nos offres",
  },
  {
    id:'3',
    name: "Pantalons",
    slug: "c-pantalon",
    category: "Vetement",
    image: "image/m12.jpg", // 679px × 829px
    price: 170,
    countInStock: 11,
    brand: "Nike",
    rating: 4.5,
    numReviews: 20,
    description: "Une marque qui vous rend encore et encore plus belle ",
  },
  {
    id:'4',
    name: "La Sape Chez nous",
    slug: "d-panta",
    category: "Vetement",
    image: "image/m13.jpg", // 679px × 829px
    price: 99,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Toujours à votre service",
  },
  {
    id:'5',
    name: "La Sape Chez nous",
    slug: "d-panta",
    category: "Vetement",
    image: "image/m14.jpg", // 679px × 829px
    price: 99,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Toujours à votre service",
  },
  {
    id:'6',
    name: "Les soutiens  Gorge",
    slug: "f-soutiens",
    category: "Vetement",
    image: "image/m15.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Proteger vous ",
  },
  {
    id:'7',
    name: "Avoir une bonne poitrine ",
    slug: "m-soutien",
    category: "Vetement",
    image: "image/m16.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Votre beauté notre priorité ",
  },
  {
    id:'8',
    name: "Qu'attendez-vous pour vous rendre belle",
    slug: "les-meilleures-soutien",
    category: "Vetement",
    image: "image/m17.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Bon prix ici ",
  },
  {
    id:'9',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m18.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'10',
    name:"C'est Été ",
    slug: "dispo",
    category: "Vetement",
    image: "image/m19.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'11',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m20.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'13',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m22.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'14',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m23.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'14',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m24.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'15',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m25.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'16',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m26.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'17',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m27.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'18',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m28.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'19',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m29.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'20',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m30.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'21',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m31.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'22',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m32.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'23',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m33.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'24',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/34.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'25',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m35.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'26',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m37.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'27',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m38.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'28',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m39.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'29',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/m40.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'30',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/mn1.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'31',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/mn2.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'32',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/mn3.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'33',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/mn4.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'34',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/mn5.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'45',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/mn6.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'69',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/mn7.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'89',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/mn8.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  {
    id:'858',
    name:"C'est Été ",
    slug: "les-prix-sont-ouf",
    category: "Vetement",
    image: "image/mn9.jpg", // 679px × 829px
    price: 30,
    countInStock: 10,
    brand: "Na marque de ouf!",
    rating: 4.5,
    numReviews: 18,
    description: "Beneficiez nos 'Été  ",
  },
  
]



// };
// export default data;
